org: sudminimal
app: mionir
service: mionir
frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.9
  tags:
    Project: "https://www.github.com/sudhanshu-chauhan/mionir"
    Environment: "prod"
    Revision: "prod"

functions:
  hello:
    handler: src/handler.hello
    events:
      - httpApi:
          path: /
          method: get
