org: sudminimal
app: mionir
service: mionir
frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.9

functions:
  hello:
    handler: src/handler.hello
    events:
      - httpApi:
          path: /
          method: get
